'use strict';

const crypto = require('node:crypto');
const { entities, entityNames, getEntity } = require('./schema');

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

class BoardService {
  constructor(store) {
    this.store = store;
  }

  describeSchema() {
    return { entities };
  }

  async list(entityName, filters = {}, limit = 100) {
    const schema = getEntity(entityName);
    const normalizedLimit = Number(limit);
    if (!Number.isInteger(normalizedLimit) || normalizedLimit < 1 || normalizedLimit > 1000) {
      throw new Error('limit must be an integer between 1 and 1000');
    }
    for (const key of Object.keys(filters)) {
      if (!schema.fields[key]) throw new Error(`Unknown filter field '${key}'`);
    }
    const data = await this.store.read();
    return data[entityName]
      .filter((record) => Object.entries(filters).every(([key, value]) => record[key] === value))
      .slice(0, normalizedLimit);
  }

  async get(entityName, id) {
    getEntity(entityName);
    this.validateUuid(id, 'id');
    const data = await this.store.read();
    const record = data[entityName].find((item) => item.id === id);
    if (!record) throw new Error(`${entityName} record '${id}' was not found`);
    return record;
  }

  async create(entityName, values) {
    const schema = getEntity(entityName);
    this.requireObject(values, 'values');
    return this.store.mutate((data) => {
      const record = this.normalizeValues(schema, values, false);
      record.id = values.id || crypto.randomUUID();
      this.validateUuid(record.id, 'id');
      if ('created_at' in schema.fields) record.created_at = new Date().toISOString();
      this.validateRequired(schema, record);
      this.validateReferences(data, schema, record);
      this.validateUnique(data, entityName, schema, record);
      if (data[entityName].some((item) => item.id === record.id)) {
        throw new Error(`${entityName} record '${record.id}' already exists`);
      }
      data[entityName].push(record);
      return record;
    });
  }

  async update(entityName, id, values) {
    const schema = getEntity(entityName);
    this.validateUuid(id, 'id');
    this.requireObject(values, 'values');
    if (Object.keys(values).length === 0) throw new Error('values must contain at least one field');
    return this.store.mutate((data) => {
      const index = data[entityName].findIndex((item) => item.id === id);
      if (index === -1) throw new Error(`${entityName} record '${id}' was not found`);
      const updates = this.normalizeValues(schema, values, true);
      const record = { ...data[entityName][index], ...updates };
      this.validateRequired(schema, record);
      this.validateReferences(data, schema, record);
      this.validateUnique(data, entityName, schema, record, id);
      data[entityName][index] = record;
      return record;
    });
  }

  async delete(entityName, id) {
    getEntity(entityName);
    this.validateUuid(id, 'id');
    return this.store.mutate((data) => {
      const index = data[entityName].findIndex((item) => item.id === id);
      if (index === -1) throw new Error(`${entityName} record '${id}' was not found`);
      for (const [otherName, otherSchema] of Object.entries(entities)) {
        for (const [field, definition] of Object.entries(otherSchema.fields)) {
          if (definition.references !== entityName) continue;
          const dependent = data[otherName].find((item) => item[field] === id);
          if (dependent) {
            throw new Error(`Cannot delete ${entityName} '${id}': referenced by ${otherName} '${dependent.id}'`);
          }
        }
      }
      const [record] = data[entityName].splice(index, 1);
      return record;
    });
  }

  normalizeValues(schema, values, updating) {
    const record = {};
    for (const [field, value] of Object.entries(values)) {
      const definition = schema.fields[field];
      if (!definition) throw new Error(`Unknown field '${field}'`);
      if (updating && definition.generated) throw new Error(`Field '${field}' cannot be updated`);
      if (field === 'created_at') throw new Error("Field 'created_at' is generated by the server");
      if (value === null) {
        if (!definition.nullable) throw new Error(`Field '${field}' cannot be null`);
        record[field] = null;
        continue;
      }
      if (definition.type === 'uuid') this.validateUuid(value, field);
      if (definition.type === 'string') {
        if (typeof value !== 'string') throw new Error(`Field '${field}' must be a string`);
        if (definition.maxLength && value.length > definition.maxLength) {
          throw new Error(`Field '${field}' must be at most ${definition.maxLength} characters`);
        }
      }
      record[field] = value;
    }
    return record;
  }

  validateRequired(schema, record) {
    for (const [field, definition] of Object.entries(schema.fields)) {
      if (definition.required && (record[field] === undefined || record[field] === null || record[field] === '')) {
        throw new Error(`Field '${field}' is required`);
      }
    }
  }

  validateReferences(data, schema, record) {
    for (const [field, definition] of Object.entries(schema.fields)) {
      const value = record[field];
      if (!definition.references || value === undefined || value === null) continue;
      if (!data[definition.references].some((item) => item.id === value)) {
        throw new Error(`Field '${field}' references missing ${definition.references} record '${value}'`);
      }
    }
  }

  validateUnique(data, entityName, schema, record, excludeId) {
    for (const fields of schema.unique || []) {
      const conflict = data[entityName].find((item) =>
        item.id !== excludeId && fields.every((field) => item[field] === record[field]));
      if (conflict) throw new Error(`Fields (${fields.join(', ')}) must be unique for ${entityName}`);
    }
  }

  validateUuid(value, field) {
    if (typeof value !== 'string' || !UUID_PATTERN.test(value)) {
      throw new Error(`Field '${field}' must be a valid UUID`);
    }
  }

  requireObject(value, name) {
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
      throw new Error(`${name} must be an object`);
    }
  }
}

module.exports = { BoardService, entityNames };

